version: "3.9"

services:
  db:
    image: postgres:15
    container_name: inamoo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inamoo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inamoo-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inamoo-app
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/inamoo"
      VITE_API_BASE_URL: "http://localhost:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn dev --host 0.0.0.0
    ports:
      - "5173:5173"
    networks:
      - inamoo-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inamoo-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: inamoo
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - inamoo-net

  admin:
    image: node:20
    container_name: inamoo-admin
    working_dir: /app
    restart: always
    ports:
      - "5174:5174"
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:8080"
    volumes:
      - ./admin:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"

volumes:
  pgdata:

networks:
  inamoo-net:
    driver: bridge
