version: "3.9"

services:
  db:
    image: postgres:15
    container_name: inamoo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inamoo
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inamoo-app
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/inamoo"
    volumes:
      - ./:/app
    command: yarn dev --host 0.0.0.0
